### ISSUE TITLE
Please provide binaries.

### ISSUE THREAD

**Issue by MariasStory** [dr-anoroc/rawccopy#1]

**Comment by dr-anoroc** [comment]
I intentionally did not provide binaries to avoid problems with virus checkers. Before I started this project, I was a happy user of [rawcopy](https://github.com/jschicht/RawCopy). But then I ran into all sorts of problems with malware false positives as explained [here](https://github.com/jschicht/RawCopy/issues/25). So now that I have rewritten the whole thing, I want to avoid ending up in the same situation.
And I guess it's not such a big deal to compile it, right?

**Comment by Aaron-Ritter-IDEXX** [comment]
My intuition is that modern, reputation-based scanners will consider the program more suspicious if there are fewer users of it, that is, if everybody produces minor differences in the binary such that it's unique to their system. I'm planning on distributing to a few thousand machines with a variety of scanners, so there's going to be some exposure of whatever binary I produce, at least.

**Comment by dr-anoroc** [comment]
Back when I had to abandon the original rawcopy, I did some research on why it was picked up by malware scanners. I found two pointers. The first was that the executable file (the binary) contained some highly recognizable fingerprints. This is easy to understand, as it is written in [AutoIt](https://www.autoitscript.com/site/), which is a -very impressive- language for automating interactions with the Windows GUI. I guess this is essentially an interpreted language, even if you can compile it into binaries. When doing that you end up with a condensed version of the source code and a rather large run-time library. The two taken together should be highly "recognizable". No complaints though, because I was a happy user for many years.
The second, and more important, pointer was that apparently rawcopy had been included in some malware bundles. This is also understandable (from a hacker's point of view), because if you've gained access to a machine, having the possibility to copy system files, even while they're in use or locked should definitely be an interesting feature.

**Comment by Aaron-Ritter-IDEXX** [comment]
Ooh yeah, I could definitely see that giving it a "bad rep" from a scanner's perspective. Maybe it is best that there's no official binary, then.

**Comment by dr-anoroc** [comment]
Will not fix this as commented before.

**Comment by ner00** [comment]
First of all, great work @dr-anoroc

Secondly, while compiling the binaries is perfectly fine, in practice it is logistically not simple at all. I was looking for such a tool, or rather an alternative to VSS-based copying, but I do not code much at all. I do not have a dev environment like it is assumed and so, while there are many ways to go about this, I went with the most practical for me but while possibly not the more efficient:
- Use (slow) VM to avoid unwarranted clutter in the host system;
- Download Visual Studio + deps (~4GB bandwidth);
- Install Visual Studio + deps (~8GB disk space);

In the end, compiling was not a big deal but what it entailed actually was. And as I don't wish that kind of redundancy on anyone else in the same situation, here are the binaries:
[RawCCopy v0.1.7_x86.zip](https://github.com/dr-anoroc/rawccopy/files/10675804/RawCCopy.v0.1.7_x86.zip)
[RawCCopy v0.1.7_x64.zip](https://github.com/dr-anoroc/rawccopy/files/10675805/RawCCopy.v0.1.7_x64.zip)

Alternatively: https://github.com/ner00/rawccopy/releases (might eventually disappear)

**Comment by dr-anoroc** [comment]
Thanks for the feedback @ner00 . Wasn't even sure people were still using it.
The irony of the thing is that I was using it myself on a corporate laptop for backing up pst files, but a couple of months ago they revoked the admin rights, so I can't use it any longer :laughing: 

In any case, the question of binaries has been discussed before and I see you're point of course. Your fork is appreciated, and there is also @spectatorBH's [fork](https://github.com/spectatorBH/rawccopy), which includes a yaml script to do the build.

**Comment by ner00** [comment]
> there is also @spectatorBH's [fork](https://github.com/spectatorBH/rawccopy)

I wish I had known about this before going through all that trouble 😅
